// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSN7wdJEbLt6CQH_GD5CtGRQzqy8ybTkU',
    appId: '1:697099061435:web:b8f059af022f5ecf44c19e',
    messagingSenderId: '697099061435',
    projectId: 'fluttercabrera',
    authDomain: 'fluttercabrera.firebaseapp.com',
    storageBucket: 'fluttercabrera.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvAgTd0hd1panHD5f6g63MQ5XJS0Nn358',
    appId: '1:697099061435:android:c1f953f0ba872c0b44c19e',
    messagingSenderId: '697099061435',
    projectId: 'fluttercabrera',
    storageBucket: 'fluttercabrera.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0eFGfMeAk62xfuyLDDvEILbdzntMf_wk',
    appId: '1:697099061435:ios:be51b7439f53c17d44c19e',
    messagingSenderId: '697099061435',
    projectId: 'fluttercabrera',
    storageBucket: 'fluttercabrera.appspot.com',
    iosClientId: '697099061435-o517s4q91oektc10so0vicodm4620q18.apps.googleusercontent.com',
    iosBundleId: 'com.jhoncabrera.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0eFGfMeAk62xfuyLDDvEILbdzntMf_wk',
    appId: '1:697099061435:ios:193d06e0f35ab13644c19e',
    messagingSenderId: '697099061435',
    projectId: 'fluttercabrera',
    storageBucket: 'fluttercabrera.appspot.com',
    iosClientId: '697099061435-8m0jcesi3nguepl0653lm8dms0fgrhlc.apps.googleusercontent.com',
    iosBundleId: 'com.jhoncabrera.crudFirebase.RunnerTests',
  );
}
